// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file MapElement.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _MAPELEMENT_H_
#define _MAPELEMENT_H_

// TODO Poner en el contexto.

#include <stdint.h>
#include <array>
#include <string>
#include <vector>
#include <map>
#include <bitset>

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#define eProsima_user_DllExport __declspec( dllexport )
#else
#define eProsima_user_DllExport
#endif
#else
#define eProsima_user_DllExport
#endif

#if defined(_WIN32)
#if defined(EPROSIMA_USER_DLL_EXPORT)
#if defined(MapElement_SOURCE)
#define MapElement_DllAPI __declspec( dllexport )
#else
#define MapElement_DllAPI __declspec( dllimport )
#endif // MapElement_SOURCE
#else
#define MapElement_DllAPI
#endif
#else
#define MapElement_DllAPI
#endif // _WIN32

namespace eprosima
{
    namespace fastcdr
    {
        class Cdr;
    }
}


/*!
 * @brief This class represents the structure MapElement defined by the user in the IDL file.
 * @ingroup MAPELEMENT
 */
class MapElement
{
public:

    /*!
     * @brief Default constructor.
     */
    eProsima_user_DllExport MapElement();

    /*!
     * @brief Default destructor.
     */
    eProsima_user_DllExport ~MapElement();

    /*!
     * @brief Copy constructor.
     * @param x Reference to the object MapElement that will be copied.
     */
    eProsima_user_DllExport MapElement(const MapElement &x);

    /*!
     * @brief Move constructor.
     * @param x Reference to the object MapElement that will be copied.
     */
    eProsima_user_DllExport MapElement(MapElement &&x);

    /*!
     * @brief Copy assignment.
     * @param x Reference to the object MapElement that will be copied.
     */
    eProsima_user_DllExport MapElement& operator=(const MapElement &x);

    /*!
     * @brief Move assignment.
     * @param x Reference to the object MapElement that will be copied.
     */
    eProsima_user_DllExport MapElement& operator=(MapElement &&x);

    /*!
     * @brief This function sets a value in member idx
     * @param _idx New value for member idx
     */
    eProsima_user_DllExport void idx(uint32_t _idx);

    /*!
     * @brief This function returns the value of member idx
     * @return Value of member idx
     */
    eProsima_user_DllExport uint32_t idx() const;

    /*!
     * @brief This function returns a reference to member idx
     * @return Reference to member idx
     */
    eProsima_user_DllExport uint32_t& idx();

    /*!
     * @brief This function copies the value in member key
     * @param _key New value to be copied in member key
     */
    eProsima_user_DllExport void key(const std::string &_key);

    /*!
     * @brief This function moves the value in member key
     * @param _key New value to be moved in member key
     */
    eProsima_user_DllExport void key(std::string &&_key);

    /*!
     * @brief This function returns a constant reference to member key
     * @return Constant reference to member key
     */
    eProsima_user_DllExport const std::string& key() const;

    /*!
     * @brief This function returns a reference to member key
     * @return Reference to member key
     */
    eProsima_user_DllExport std::string& key();
    /*!
     * @brief This function sets a value in member value
     * @param _value New value for member value
     */
    eProsima_user_DllExport void value(double _value);

    /*!
     * @brief This function returns the value of member value
     * @return Value of member value
     */
    eProsima_user_DllExport double value() const;

    /*!
     * @brief This function returns a reference to member value
     * @return Reference to member value
     */
    eProsima_user_DllExport double& value();


    /*!
     * @brief This function returns the maximum serialized size of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function returns the serialized size of a data depending on the buffer alignment.
     * @param data Data which is calculated its serialized size.
     * @param current_alignment Buffer alignment.
     * @return Serialized size.
     */
    eProsima_user_DllExport static size_t getCdrSerializedSize(const MapElement& data, size_t current_alignment = 0);


    /*!
     * @brief This function serializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serialize(eprosima::fastcdr::Cdr &cdr) const;

    /*!
     * @brief This function deserializes an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void deserialize(eprosima::fastcdr::Cdr &cdr);



    /*!
     * @brief This function returns the maximum serialized size of the Key of an object
     * depending on the buffer alignment.
     * @param current_alignment Buffer alignment.
     * @return Maximum serialized size.
     */
    eProsima_user_DllExport static size_t getKeyMaxCdrSerializedSize(size_t current_alignment = 0);

    /*!
     * @brief This function tells you if the Key has been defined for this type
     */
    eProsima_user_DllExport static bool isKeyDefined();

    /*!
     * @brief This function serializes the key members of an object using CDR serialization.
     * @param cdr CDR serialization object.
     */
    eProsima_user_DllExport void serializeKey(eprosima::fastcdr::Cdr &cdr) const;

private:
    uint32_t m_idx;
    std::string m_key;
    double m_value;
};

#endif // _MAPELEMENT_H_